function T = rocky_load_tables(repoRoot)
%ROCKY_LOAD_TABLES Load every derived Rocky table into one struct.
%
%   T = ROCKY_LOAD_TABLES()          assumes this file sits in <repo>/matlab
%   T = ROCKY_LOAD_TABLES(repoRoot)  explicit repo root
%
%   Every field is a MATLAB table read from the Parquet stores under
%   data/derived/ (the same files the Python figure scripts read; see
%   docs/notes/data_inspection.md for the layer map). Open any field in the
%   Variable Editor to inspect. Date columns are converted to datetime in
%   place where they arrive as strings.
%
%   Fields:
%     session_summary      per session x method (resort), yield + medians
%     session_metrics_ofs  same shape for the Plexon reference sort
%     longitudinal         per session, sorted + sorting-free layers (36 cols)
%     trends               Spearman trends per array x metric
%     units_long           one row per unit, methods 'resort' and 'ofs'
%     methods_long         one row per unit across the five snippet methods
%     curation             units with SI quality metrics + UnitRefine labels
%     agreement            per-channel ARI between method pairs
%     jaccard              per-unit best-Jaccard matches between methods
%     electrode_summary    per array x channel x year spatial summary
%     events_electrode     sorting-free per electrode x session (I1)
%     events_electrode_i2  same for implant 2 (2025)
%     giants, giant_sites  giant-event taxonomy and recurring sites
%     impedance            52-date potentiostat record, both candidate maps
%     impedance_qc         per array-date QC flags
%     sens_sweep, sens_rho gate-sensitivity sweep and trend stability
%     cohort               cross-animal session table (filter subject=="Rocky")
%
%   Provenance: generated by notebooks/scratch_rocky_*.py et al.; this loader
%   only reads, never writes.

if nargin < 1
    here = fileparts(mfilename("fullpath"));      % <repo>/matlab
    repoRoot = fileparts(here);
end
D = fullfile(repoRoot, "data", "derived");
if ~isfolder(D)
    error("rocky_load_tables:noData", ...
        "data/derived not found under %s - run from the repo checkout", repoRoot);
end

r = @(varargin) parquetread(fullfile(D, varargin{:}));

T = struct();
T.repoRoot            = string(repoRoot);
T.session_summary     = fixdates(r("rocky", "session_summary.parquet"));
T.session_metrics_ofs = fixdates(r("rocky", "session_metrics_ofs.parquet"));
T.longitudinal        = fixdates(r("rocky", "longitudinal_metrics.parquet"));
T.trends              = r("rocky", "longitudinal_trends.parquet");
T.units_long          = fixdates(r("rocky", "units_long.parquet"));
T.methods_long        = fixdates(r("rocky", "methods_long.parquet"));
T.curation            = fixdates(r("rocky", "curation_labels.parquet"));
T.agreement           = fixdates(r("rocky", "method_agreement.parquet"));
T.jaccard             = fixdates(r("rocky", "method_jaccard.parquet"));
T.electrode_summary   = r("rocky", "electrode_summary.parquet");
T.events_electrode    = fixdates(r("rocky", "events_electrode.parquet"));
T.events_electrode_i2 = fixdates(r("rocky_i2", "events_electrode.parquet"));
T.giants              = fixdates(r("rocky", "giant_events.parquet"));
T.giant_sites         = r("rocky", "giant_sites.parquet");
T.impedance           = fixdates(r("rocky", "impedance_long_full.parquet"));
T.impedance_qc        = fixdates(r("rocky", "impedance_qc.parquet"));
T.sens_sweep          = fixdates(r("rocky", "sensitivity_sweep.parquet"));
T.sens_rho            = r("rocky", "sensitivity_rho.parquet");
T.cohort              = fixdates(r("cohort", "cohort_sessions.parquet"));

fprintf("rocky_load_tables: %d tables from %s\n", ...
    numel(fieldnames(T)) - 1, D);
end


function t = fixdates(t)
%FIXDATES Convert a string/char 'date' column to datetime, in place.
if ismember("date", t.Properties.VariableNames)
    c = t.date;
    if isstring(c) || iscellstr(c) || ischar(c)          %#ok<ISCLSTR>
        t.date = datetime(string(c), "InputFormat", "yyyy-MM-dd");
    end
end
end
